#!/usr/bin/env python3
"""Pack the fork-badge sprites into a single sheet.

The timeline previously loaded 24 individual badge/pill images; over HTTP/1.1
(local preview) they waterfall. One sheet = one request. Artwork is untouched
— the individual crops stay in public/upgrades/ (the export generator and this
script both read them).

Writes:
  public/upgrades/badges.webp   the sheet
  src/data/badge-sprites.ts     coordinates for the CSS background-position math

Re-run when badge artwork changes.
"""

import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "public", "upgrades")

IDS = (
    [f"el-{i}" for i in range(1, 15)]
    + [f"cl-{i}" for i in range(1, 3)]
    + [f"post-{i}" for i in range(1, 7)]
    + ["merge-pill", "merge-pill-left"]
)

PAD = 4


def main():
    imgs = {i: Image.open(os.path.join(ASSETS, f"{i}.webp")) for i in IDS}
    width = sum(im.width for im in imgs.values()) + PAD * (len(imgs) + 1)
    height = max(im.height for im in imgs.values()) + 2 * PAD

    sheet = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    sprites = {}
    x = PAD
    for i in IDS:
        im = imgs[i]
        sheet.alpha_composite(im, (x, PAD))
        sprites[i] = {"x": x, "y": PAD, "w": im.width, "h": im.height}
        x += im.width + PAD

    out = os.path.join(ASSETS, "badges.webp")
    sheet.save(out, quality=90, method=6)

    lines = [
        "// generated by scripts/generate-badge-sprites.py — do not edit by hand",
        "export const badgeSheet = {",
        '  src: "/upgrades/badges.webp",',
        f"  width: {width},",
        f"  height: {height},",
        "  sprites: {",
    ]
    for i, s in sprites.items():
        lines.append(f'    "{i}": {{ x: {s["x"]}, y: {s["y"]}, w: {s["w"]}, h: {s["h"]} }},')
    lines += ["  },", "};", ""]
    ts_path = os.path.join(ROOT, "src", "data", "badge-sprites.ts")
    with open(ts_path, "w") as f:
        f.write("\n".join(lines))

    print(f"wrote {out} ({os.path.getsize(out) / 1024:.1f} KB, {width}x{height}, {len(IDS)} sprites)")
    print(f"wrote {ts_path}")


if __name__ == "__main__":
    main()
